### ISSUE TITLE
Not running after pylint installation and configuration

### ISSUE THREAD

**Issue by trombini77** [Grafluxe/pylinter#1]
Hi.
I did a clean install of python, after I installed the pip and after the pylint.
All of them running without problems in command line prompt and after installed this extension in my Brackets I inserted the pylint location in the brackets.json configuration file like this:

    "pylinter.pylintPath": "C:\\Users\\leand\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\pylint.exe",
    "pylinter.outputPattern": "{msg_id} > {msg} [{symbol} @ {line},{column}]",

after I did it no more error messages of extension running fail but when I open a .py file is not showing nothing about pylint.
I run the pylint from command line in the same file and it showed messages, but it still not working in Brackets.
My Brackets version:
sprint 8 version 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
timestamp version: Wed Nov 02 2016 12:07:29 GMT+0000

Thanks.

**Comment by trombini77** [comment]
![pylint](https://cloud.githubusercontent.com/assets/13336060/21566497/b6fbd144-ce8a-11e6-9fc8-4cbb9a0b3a00.jpg)

**Comment by grafluxe** [comment]
Hi @trombini77,

I'm sorry to hear that you're having issues with my extension. I'll do my best to help you resolve it.

Things are working fine on my Windows VM (even after updating the Python and Pylint versions). To help me further test, can you provide a gist of the code that you're running into issues with?

Also, can you share with me the output of the following command?:

```
C:\Users\leand\AppData\Local\Programs\Python\Python36-32\Scripts\pylint.exe --version
```

Thanks and happy new year,
